default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: vertical_drama_development

test:
  <<: *default
  database: vertical_drama_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>